### PR TITLE
Update 2024 git lecture

### PR DESCRIPTION
**Pull request by LMBishop**
Current changes from last year:
- Most code blocks updated to use one of `bash` or `console` syntax highlighting
- A more accurate description of how commits are represented by Git (line 90)
- Added captions (and some basic CSS for the `figure` / `figcaption` elements) to most diagrams
- Added a new section on merging and rebasing

Todo:

~~- [ ] Exercises (?)~~

### CODE REVIEW

**Comment by codemicro** [comment]
`console` syntax highlighting is a thing?? ***i'm in love***

**Comment by codemicro** [comment]
All looks good to me :)

**Comment by codemicro** [comment]
With respect to some exercises, that seems like something to include in week 8 as opposed to here, especially since that's a little more involved on topics like working with other people

**Comment by LMBishop** [comment]
> `console` syntax highlighting is a thing?? _**i'm in love**_

Yep! It seems like the grammar is implemented in some capacity on GitHub too

```console
leonardo@bongo:~ $ echo "Hello\!" > hello
leonardo@bongo:~ $ cowsay -f tux $(cat hello)
 ________
< Hello! >
 --------
   \
    \
        .--.
       |o_o |
       |:_/ |
      //   \ \
     (|     | )
    /'\_   _/`\
    \___)=(___/
```



> With respect to some exercises, that seems like something to include in week 8 as opposed to here, especially since that's a little more involved on topics like working with other people

Yeah makes sense, I'll remove that section

I'll also unmark the PR as a draft. If you need any more help adding / changing sections then let me know - my weekend is (mostly) free!

**Comment by LMBishop** [comment]
Oh, one other thing. I don't actually know what the `drawio-diagram` attribute means, all the new figures I added have the same value. It's probably worth removing those attributes

**Pull request merged**
